### ISSUE TITLE
Incorrect choice of encoding Cyrillic characters resulting in UnicodeDecodeError

### ISSUE THREAD

**Issue by AlexArcPy** [tylerwince/flake8-bandit#4] opened 2018-10-04 22:02 UTC
**Description**

I have:
* Windows 10
* Clean conda Python 3.6 env

I ran
`pip install flake8-bandit`

and got
`Successfully installed GitPython-2.1.11 PyYAML-3.13 bandit-1.5.1 flake8-3.5.0 flake8-bandit-1.0.2 flake8-polyfill-1.0.2 gitdb2-2.0.4 mccabe-0.6.1 pbr-4.3.0 pycodestyle-2.3.1 pyflakes-1.6.0 six-1.11.0 smmap2-2.0.4 stevedore-1.29.0`

I have a Python module with the following contents:

```python
# -*- coding: UTF-8 -*-
"""Module docstring."""
print('hello') # э
```

I run 
`flake8 C:\Development\Flake8PluginDev\foo.py`

an error is produced.
```
(BanditDebug) C:\Users\user>flake8 C:\Development\Flake8PluginDev\foo.py
Traceback (most recent call last):
  File "c:\anaconda3\envs\banditdebug\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\anaconda3\envs\banditdebug\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Anaconda3\envs\BanditDebug\Scripts\flake8.exe\__main__.py", line 9, in <module>
  File "c:\anaconda3\envs\banditdebug\lib\site-packages\flake8\main\cli.py", line 16, in main
    app.run(argv)
  File "c:\anaconda3\envs\banditdebug\lib\site-packages\flake8\main\application.py", line 396, in run
    self._run(argv)
  File "c:\anaconda3\envs\banditdebug\lib\site-packages\flake8\main\application.py", line 384, in _run
    self.run_checks()
  File "c:\anaconda3\envs\banditdebug\lib\site-packages\flake8\main\application.py", line 310, in run_checks
    self.file_checker_manager.run()
  File "c:\anaconda3\envs\banditdebug\lib\site-packages\flake8\checker.py", line 321, in run
    self.run_serial()
  File "c:\anaconda3\envs\banditdebug\lib\site-packages\flake8\checker.py", line 305, in run_serial
    checker.run_checks()
  File "c:\anaconda3\envs\banditdebug\lib\site-packages\flake8\checker.py", line 579, in run_checks
    self.run_ast_checks()
  File "c:\anaconda3\envs\banditdebug\lib\site-packages\flake8\checker.py", line 486, in run_ast_checks
    checker = self.run_check(plugin, tree=ast)
  File "c:\anaconda3\envs\banditdebug\lib\site-packages\flake8\checker.py", line 435, in run_check
    return plugin['plugin'](**arguments)
  File "c:\anaconda3\envs\banditdebug\lib\site-packages\flake8_bandit.py", line 35, in __init__
    self._load_source()
  File "c:\anaconda3\envs\banditdebug\lib\site-packages\flake8_bandit.py", line 73, in _load_source
    self.source = f.read()
  File "c:\anaconda3\envs\banditdebug\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 68: character maps to <undefined>
```

**To Reproduce**

If I have 

```python
# -*- coding: UTF-8 -*-
"""Module docstring."""
print('hello') # й
```

I run 
`flake8 C:\Development\Flake8PluginDev\foo.py`

and get
`C:\Development\Flake8PluginDev\foo.py:3:15: E261 at least two spaces before inline comment`

It works fine.

Now if we change the Cyrillic `# й` comment into either the `# э`, `# я`, or `# с` (with all three characters typed with Russian keyboard layout, mind [Russian C](https://en.wikipedia.org/wiki/Es_(Cyrillic))) and run
`flake8 C:\Development\Flake8PluginDev\foo.py`

an error is produced.

It seems as `bandit` has problems with only three Russian letters `эяс` because when running the `flake8` with the comment containing all Russian letters except `эяс`, it works fine:

```python
# -*- coding: UTF-8 -*-
"""Module docstring."""
print('hello') # йцукенгшщзхъфывапролджё
```

**Expected behavior**
Bandit should handle all Cyrillic characters without throwing `UnicodeDecodeError` error.

**Bandit version**
```
(BanditDebug) C:\Users\user>bandit --version
bandit 1.5.1
  python version = 3.6.6 |Anaconda, Inc.| (default, Jun 28 2018, 11:21:07) [MSC v.1900 32 bit (Intel)]

flake8          3.5.0
flake8-bandit   1.0.2
```

**Comment by sobolevn** [comment] 2018-10-05 06:56
Hi, @tylerwince ! Thanks for writing this plugin. We are using it as a dependency in our linter: https://github.com/wemake-services/wemake-python-styleguide

So, this issue also affects us as well.

I am pretty sure that this error is caused by these lines: 
https://github.com/tylerwince/flake8-bandit/blob/master/flake8_bandit.py#L62-L73

What can be done it improve it?
1. We can just receive `lines` from `flake8` http://flake8.pycqa.org/en/latest/plugin-development/plugin-parameters.html#indicating-desired-data they should be already in the correct format/encoding
2. We can write some tests that russian letters now work, this will ensure that this won't happen again

@tylerwince Does this sound reasonable to you?
@AlexArcPy Are you willing to provide a PR? This would be awesome!

**Comment by AlexArcPy** [comment] 2018-10-05 07:41
@sobolevn , I've tested that changing line 72
`with open(self.filename) as f:`
to
`with io.open(self.filename, 'r', encoding='utf-8') as f:`

makes it working with `utf-8` files including having Cyrillic chars (both with magic encoding and without). Tested on both 2.7 and 3.6. 

Nikita, did you mean to write a test in the `wemake-python-styleguide` repo?

**Comment by sobolevn** [comment] 2018-10-05 08:01
@AlexArcPy no, I meant writing tests in this repo. Currently it does not have any 🙁 

The problem with `with io.open(self.filename, 'r', encoding='utf-8') as f:` is that you are hardcoding an encoding. Encoding might differ for different locales and users. So, we should guess it instead.

`flake8` does this for you, however. So, there is no need to do anything except just receiving a new parameter in the constructor.

**Comment by AlexArcPy** [comment] 2018-10-05 10:22
@sobolevn , good point on encoding! I am not yet confident with `flake8` development so I'd have hard time working on `receiving a new parameter in the constructor.` :)
Regarding the tests in this repo, we won't be able to add any unless we know the pull request could be accepted - let's wait for @tylerwince to respond first?
Also, if we will have tests, would it be possible to add CI operation - the current repo does not seem to have any associated unless I am missing something.

**Comment by tylerwince** [comment] 2018-10-05 14:06
Cheers @sobolevn and @AlexArcPy -- Thanks for the dialog above. 

I would definitely welcome a PR for some tests and can get some CI stuff going with TravisCI once we they exist. 

As for the encoding stuff - I have been meaning to change the way this works for a while. Unfortunately, different editors require the plugin to work differently to lint the file. I haven't had the time to go back and refactor lines https://github.com/tylerwince/flake8-bandit/blob/master/flake8_bandit.py#L64-L69 but that is where the issue lies. 

If one of you guys has a good idea on how to remove the requirement of the additional file, I'd gladly accept a PR, otherwise I will take a crack at it this weekend.

Thanks for using the plugin! Glad it is useful

**Comment by tylerwince** [comment] 2019-01-05 18:20
@AlexArcPy @sobolevn I apologize for the delay on this. I am just getting around to working on this project. I have updated the way we parse the file for the next version (see branch https://github.com/tylerwince/flake8-bandit/tree/v2.0). It appears to have fixed the original issue on this so I suggest we close it and I am going to open up a new issue for testing. 

Please reopen if you are still experiencing the same issue.

**Closed as completed by tylerwince** 2019-01-05 18:20 UTC
